#!/bin/sh
DEV_WAIT=3
sudo wpa_supplicant -B -i wlp46s0 -c /etc/wpa_supplicant/wpa_supplicant.conf -D nl80211
echo sleeping for $DEV_WAIT
sleep $DEV_WAIT
sudo dhclient -v -4 -nw wlp46s0 ; sudo sysctl net.ipv6.conf.all.disable_ipv6=1; sleep 1; timeout 2 ping google.com
